# Generated by Django 5.2 on 2026-07-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("gender", models.CharField(blank=True, max_length=10)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("city", models.CharField(max_length=100)),
                ("current_class", models.CharField(max_length=50)),
                ("school", models.CharField(blank=True, max_length=200)),
                ("course", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=50)),
                ("mode", models.CharField(max_length=50)),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
